// <auto-generated />
using System;
using AttendanceAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AttendanceAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AttendanceAPI.Models.AttendanceRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("CheckInFaceVerified")
                        .HasColumnType("bit");

                    b.Property<bool>("CheckInGeoVerified")
                        .HasColumnType("bit");

                    b.Property<double?>("CheckInLatitude")
                        .HasColumnType("float");

                    b.Property<double?>("CheckInLongitude")
                        .HasColumnType("float");

                    b.Property<int>("CheckInStatus")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CheckInTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("CheckOutFaceVerified")
                        .HasColumnType("bit");

                    b.Property<bool>("CheckOutGeoVerified")
                        .HasColumnType("bit");

                    b.Property<double?>("CheckOutLatitude")
                        .HasColumnType("float");

                    b.Property<double?>("CheckOutLongitude")
                        .HasColumnType("float");

                    b.Property<int>("CheckOutStatus")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CheckOutTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("OverallStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Date")
                        .IsUnique();

                    b.ToTable("AttendanceRecords");
                });

            modelBuilder.Entity("AttendanceAPI.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("RadiusMeters")
                        .HasColumnType("float");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("AttendanceAPI.Models.InternSerialTracker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("LastSerial")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("InternSerialTrackers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LastSerial = 0
                        });
                });

            modelBuilder.Entity("AttendanceAPI.Models.Shift", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<TimeOnly>("CheckInEarlyBefore")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("CheckInEnd")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("CheckInStart")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("CheckOutEarlyBefore")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("CheckOutEnd")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("CheckOutStart")
                        .HasColumnType("time");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Shifts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CheckInEarlyBefore = new TimeOnly(9, 0, 0),
                            CheckInEnd = new TimeOnly(9, 15, 0),
                            CheckInStart = new TimeOnly(9, 0, 0),
                            CheckOutEarlyBefore = new TimeOnly(16, 0, 0),
                            CheckOutEnd = new TimeOnly(16, 15, 0),
                            CheckOutStart = new TimeOnly(16, 0, 0),
                            Description = "9:00 AM - 4:00 PM",
                            Name = "Shift 1 - Morning"
                        },
                        new
                        {
                            Id = 2,
                            CheckInEarlyBefore = new TimeOnly(10, 0, 0),
                            CheckInEnd = new TimeOnly(10, 15, 0),
                            CheckInStart = new TimeOnly(10, 0, 0),
                            CheckOutEarlyBefore = new TimeOnly(17, 0, 0),
                            CheckOutEnd = new TimeOnly(17, 15, 0),
                            CheckOutStart = new TimeOnly(17, 0, 0),
                            Description = "10:00 AM - 5:00 PM",
                            Name = "Shift 2 - Afternoon"
                        });
                });

            modelBuilder.Entity("AttendanceAPI.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FaceDescriptor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("MentorId")
                        .HasColumnType("int");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<int?>("ShiftId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("MentorId");

                    b.HasIndex("ShiftId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FirstName = "System",
                            IsActive = true,
                            LastName = "Admin",
                            PasswordHash = "$2a$11$imegW5vSxdrcoV8F5B9k0uI/YoKxeq.XQz/CMdCYFqb4Op409q5oK",
                            Role = 0,
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("AttendanceAPI.Models.AttendanceRecord", b =>
                {
                    b.HasOne("AttendanceAPI.Models.User", "User")
                        .WithMany("AttendanceRecords")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AttendanceAPI.Models.User", b =>
                {
                    b.HasOne("AttendanceAPI.Models.Department", "Department")
                        .WithMany("Users")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AttendanceAPI.Models.User", "Mentor")
                        .WithMany("Interns")
                        .HasForeignKey("MentorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AttendanceAPI.Models.Shift", "Shift")
                        .WithMany("Users")
                        .HasForeignKey("ShiftId");

                    b.Navigation("Department");

                    b.Navigation("Mentor");

                    b.Navigation("Shift");
                });

            modelBuilder.Entity("AttendanceAPI.Models.Department", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("AttendanceAPI.Models.Shift", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("AttendanceAPI.Models.User", b =>
                {
                    b.Navigation("AttendanceRecords");

                    b.Navigation("Interns");
                });
#pragma warning restore 612, 618
        }
    }
}
